config/routes.rb
Rails.application.routes.draw do

  resources :gossips
  resources :users
  resources :cities
 
  
  get '/team', to: 'pages#team', as: 'team'
  get '/contact', to: 'pages#contact', as: 'contact'  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :gossip
	belongs_to :user
	has_many :likes
end

app/models/first_name_table.rb
class FirstNameTable < ApplicationRecord
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true, length: { in: 3..25 }
	validates :content, presence: true
	belongs_to :user
	has_many :comments
	has_many :taggossips
	has_many :tags, through: :taggossips
	has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :comment, optional: true
	belongs_to :gossip, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

app/models/privatemessage.rb
class Privatemessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggossips
	has_many :gossips, through: :taggossips
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag

end

app/models/taggossip.rb
class Taggossip < ApplicationRecord
	belongs_to :tag, optional: true
	belongs_to :gossip, optional: true
end

app/models/user.rb
class User < ApplicationRecord
	validates :first_name, presence: true , length: { maximum: 15 }
	validates :last_name, presence: true, length: { maximum: 15 }
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
	validates :age, presence: true, numericality: { only_integer: true }
	belongs_to :city
	has_many :gossips
	has_many :commments
	has_many :likes
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

    def index
        
        @cities = City.all
      end
    
      def show
        @cities = City.all
        @id_cities = City.find(params['id'])
      end
  
    def new
      
    end
  
    def create
      # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
      # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
      
    end
  
    def edit
      # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    end
  
    def update
      # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params
      # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    end
  
    def destroy
      # Méthode qui récupère le potin concerné et le détruit en base
      # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    end
  end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

    def index
      @name = params[:first_name]
      @gossips = Gossip.all
    end
  
    def show
      @gossips = Gossip.all
      @id_gossips = Gossip.find(params['id'])
    end
  
    def new
      @gossip = Gossip.last
    end
  
    def create
      # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
      # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
      
      @gossip = Gossip.new
      @gossip.title = params['gossip_title']
      @gossip.content = params['gossip_content']
      @gossip.user = User.last
  
      if @gossip.save # essaie de sauvegarder en base @gossip
        @i = "1"
        sleep 4
        redirect_to gossips_path
        @i = "0"
      else
         render :template => 'gossips/new'# sinon, il render la view new (qui est celle sur laquelle on est déjà)
  end
    end
  
    def edit
      # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    end
  
    def update
      # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params
      # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    end
  
    def destroy
      # Méthode qui récupère le potin concerné et le détruit en base
      # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def team
        
        
    end
    

    def contact

    end

    

    

    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
    @users = User.all
    @id_users = User.find(params['id'])
end

def index 
    @users = User.all
    @name = params[:first_name]
    
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/show.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Team#Yannick#Momo#Polo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to "Home", gossips_path %>
         
      </li>
      <li class="nav-item active">
        <%= link_to "Team ", team_path %>

      </li>
      <li class="nav-item active">
         <%= link_to "Contact", contact_path %>
      </li>

    </ul>
  </div>
</nav>
<center>

<div class="card">
  <div class="card-header">
<br><%=  @id_users.last_name %> <%= @id_users.first_name%>

  </div>
  <div class="card-body">
    <h5 class="card-title"> <%=  @id_users.description%><br></h5>
    <p class="card-text">  <%=  @id_users.email %><br>
    from : <%= @id_users.city.name %> </br>
    âge :  <%= link_to "#{@id_users.age}", gossips_path %></p>
    
  </div>
</div>
</center>
<style>

body { background: -webkit-linear-gradient(left, #25c481, #25b7c4);
    background: linear-gradient(to right, #25c481, #25b7c4);
    
}
</style>
       
      <br>
  </a>
        

app/views/gossips/new.html.erb
<head>
     <link rel="stylesheet" type="text/css" href="welcome.css">

   </head>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Team#Yannick#Momo#Polo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to "Home", gossips_path %>
         
      </li>
      <li class="nav-item active">
        <%= link_to "Team ", team_path %>

      </li>
      <li class="nav-item active">
         <%= link_to "Contact", contact_path %>
      </li>

    </ul>
  </div>
</nav>

<body>
<br>
<br>
<style>

body { background: -webkit-linear-gradient(left, #25c481, #25b7c4);
    background: linear-gradient(to right, #25c481, #25b7c4);

    }
</style>

<div class="row m-3">
	<% if @gossip.errors.any? %>
	<div class="alert alert-danger" role="alert">
	  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
	  <ul>
	    <% @gossip.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	  </div>
      
	<% end %>
</div>
<% if @i == "1" %>
      <div class="alert alert-success" role="alert">
	  <p> YEAH BRAAA</p>
	  
	  </div>
      <% end %>
      </div>


<div class="row m-3">
		<div class="col-sm-12 col-md-6 offset-md-3">
			<%= form_tag("/gossips", method: "post") do %>
		  <%= label_tag(:gossip_title, "Titre:") %>
		  <%= text_field_tag(:gossip_title, "", :class => 'form-control') %>
		  <br>
		  <%= label_tag(:gossip_content, "Contenu:") %>
		  <%= text_area_tag(:gossip_content, "", :class => 'form-control') %>
		  <br>
		  <%= submit_tag("Poster", :class => "btn btn-success") %>
		  </div>
	<% end %>
</div>

<div class="row m-3">

app/views/gossips/show.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Team#Yannick#Momo#Polo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to "Home", gossips_path %>
         
      </li>
      <li class="nav-item active">
        <%= link_to "Team ", team_path %>

      </li>
      <li class="nav-item active">
         <%= link_to "Contact", contact_path %>
      </li>

    </ul>
  </div>
</nav>
<center>

<div class="card">
  <div class="card-header">
<br><%=  @id_gossips.title %>

  </div>
  <div class="card-body">
    <h5 class="card-title"> <%=  @id_gossips.content %><br></h5>
    <p class="card-text">  <%=  @id_gossips.created_at %><br></p>
    <p  class="btn btn btn-primary"><%= link_to "#{@id_gossips.user.first_name}", user_path(@id_gossips.user.id) %> </p>
  </div>
</div>
</center>
<style>

body { background: -webkit-linear-gradient(left, #25c481, #25b7c4);
    background: linear-gradient(to right, #25c481, #25b7c4);
    
}
</style>
       
      <br>
  </a>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= yield %>

  </body>
</html>

app/views/pages/contact.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Team#Yannick#Momo#Polo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to "Home", gossips_path %>
         
      </li>
      <li class="nav-item active">
        <%= link_to "Team ", team_path %>

      </li>
      <li class="nav-item active">
         <%= link_to "Contact", contact_path %>
      </li>


    </ul>
  </div>
</nav>
<br><br><br><br><br><br><br>
<center>
<img src="https://i.skyrock.net/7066/57467066/pics/2329750265_1.jpg">
<br><i class="">Contactez moi les petits djeuns :D </i>
<div>06 . 95 . 46 . 60 . 80</div>
</center>
<style>

body { background: -webkit-linear-gradient(left, #25c481, #25b7c4);
    background: linear-gradient(to right, #25c481, #25b7c4);
    
}
</style>

app/views/pages/home.html.erb
<br>
<br>


<br>
<center>
<form action="/welcome" method="get">
<label> <span>Say your name to momo  ! :</span><br>
  <input type="text" placeholder="Your name" name="first_name" required/>
  <input type="submit" class="btn btn-dark" value="Confirmer" />
</form>


</center>



<style>
span {
  color : white;
}
body {
background-image : url('https://parismatch.be/app/uploads/2018/10/momo-challenge-whatsapp-Copie-1100x715.jpg');
background-size : cover;
}
</style>

app/views/pages/show.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Team#Yannick#Momo#Polo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/welcome">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/team">Team</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/contact">Contact</a>
      </li>

    </ul>
  </div>
</nav>
<center>

<div class="card">
  <div class="card-header">
<br><%=  @id_gossips.title %>

  </div>
  <div class="card-body">
    <h5 class="card-title"> <%=  @id_gossips.content %><br></h5>
    <p class="card-text">  <%=  @id_gossips.created_at %><br></p>
    <a  href="/user/<%= @id_gossips.user_id %>"  class="btn btn btn-primary"><%=  @id_gossips.user.first_name %></a>
  </div>
</div>
</center>
<style>

body { background: -webkit-linear-gradient(left, #25c481, #25b7c4);
    background: linear-gradient(to right, #25c481, #25b7c4);
    
}
</style>
       
      <br>
  </a>
        

app/views/pages/team.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Team#Yannick#Momo#Polo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to "Home", gossips_path %>
         
      </li>
      <li class="nav-item active">
        <%= link_to "Team ", team_path %>

      </li>
      <li class="nav-item active">
         <%= link_to "Contact", contact_path %>
      </li>


    </ul>
  </div>
</nav>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br><br>
<br>
<br>
<br>
<br>
<br><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<center><i style="color: white; font-size: 32px; background: black" class="">Voici notre équipe lol mdr 😇❤️😻</i></center>




<style>
body { 
background-image : url('http://loanpride.com/wp-content/uploads/2017/01/succcessful-mondays-1.jpg')
}
</style>

app/views/pages/user.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Team#Yannick#Momo#Polo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/welcome">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/team">Team</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/contact">Contact</a>
      </li>

    </ul>
  </div>
</nav>
<center>

<div class="card">
  <div class="card-header">
  <%=  @id_users.first_name %>,<%=  @id_users.last_name %>
  </div>
  <div class="card-body">
    <h5 class="card-title">Nom prénom :  <%=  @id_users.email %> </h5>
    <p class="card-text">Description : <%=  @id_users.description %><br></p>
    <a href="#" class="btn btn-primary">  age : <%=  @id_users.age %></a>
  </div>
</div>
<style>

body { background: -webkit-linear-gradient(left, #25c481, #25b7c4);
    background: linear-gradient(to right, #25c481, #25b7c4);
    
}
</style>
</center>

app/views/users/show.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Team#Yannick#Momo#Polo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to "Home", gossips_path %>
         
      </li>
      <li class="nav-item active">
        <%= link_to "Team ", team_path %>

      </li>
      <li class="nav-item active">
         <%= link_to "Contact", contact_path %>
      </li>

    </ul>
  </div>
</nav>
<center>

<div class="card">
  <div class="card-header">
<br><%=  @id_users.last_name %> <%= @id_users.first_name%>

  </div>
  <div class="card-body">
    <h5 class="card-title"> <%=  @id_users.description%><br></h5>
    <p class="card-text">  <%=  @id_users.email %><br>
    from : <%= @id_users.city.name %> </br>
    âge :  <%= link_to "#{@id_users.age}", gossips_path %></p>
    
  </div>
</div>
</center>
<style>

body { background: -webkit-linear-gradient(left, #25c481, #25b7c4);
    background: linear-gradient(to right, #25c481, #25b7c4);
    
}
</style>
       
      <br>
  </a>
        

app/views/users/user.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Team#Yannick#Momo#Polo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to "Home", gossips_path %>
         
      </li>
      <li class="nav-item active">
        <%= link_to "Team ", team_path %>

      </li>
      <li class="nav-item active">
         <%= link_to "Contact", contact_path %>
      </li>

    </ul>
  </div>
</nav>
<center>

<div class="card">
  <div class="card-header">
  <%=  @id_users.first_name %>,<%=  @id_users.last_name %>
  </div>
  <div class="card-body">
    <h5 class="card-title">Nom prénom :  <%=  @id_users.email %> </h5>
    <p class="card-text">Description : <%=  @id_users.description %><br></p>
    <a href="#" class="btn btn-primary">  age : <%=  @id_users.age %></a>
  </div>
</div>
<style>

body { background: -webkit-linear-gradient(left, #25c481, #25b7c4);
    background: linear-gradient(to right, #25c481, #25b7c4);
    
}
</style>
</center>